require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'spec/factories/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'feature', 'scenario', 'let']

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/*'

RSpec/ExampleLength:
  Max: 50

Style/FormatString:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 30

RSpec/DescribedClass:
 Enabled: false
 
Layout/TrailingEmptyLines:
  Enabled: false

Lint/Syntax:
  Enabled: true

RSpec/EmptyExampleGroup:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Layout/LineLength:
  Max: 130

Lint/UselessAssignment:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Metrics/BlockLength:
  Max: 110

Rails/SkipsModelValidations:
  Enabled: false